---
abstract: 'Tools to help make git workflows easier'
author:
  - 'Ivan Wills <ivan.wills@gmail.com>'
build_requires:
  Capture::Tiny: 0
  Test::MockTime: 0
  Test::More: 0
  Test::Warnings: 0
configure_requires:
  Module::Build: 0.42
dynamic_config: 1
generated_by: 'Module::Build version 0.4204, CPAN::Meta::Converter version 2.133380'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: App-Git-Workflow
provides:
  App::Git::Workflow:
    file: lib/App/Git/Workflow.pm
    version: 0.92
  App::Git::Workflow::Command:
    file: lib/App/Git/Workflow/Command.pm
    version: 0.92
  App::Git::Workflow::Command::BranchClean:
    file: lib/App/Git/Workflow/Command/BranchClean.pm
    version: 0.92
  App::Git::Workflow::Command::BranchGrep:
    file: lib/App/Git/Workflow/Command/BranchGrep.pm
    version: 0.92
  App::Git::Workflow::Command::Committers:
    file: lib/App/Git/Workflow/Command/Committers.pm
    version: 0.92
  App::Git::Workflow::Command::Cows:
    file: lib/App/Git/Workflow/Command/Cows.pm
    version: 0.92
  App::Git::Workflow::Command::Feature:
    file: lib/App/Git/Workflow/Command/Feature.pm
    version: 0.92
  App::Git::Workflow::Command::Files:
    file: lib/App/Git/Workflow/Command/Files.pm
    version: 0.92
  App::Git::Workflow::Command::Jira:
    file: lib/App/Git/Workflow/Command/Jira.pm
    version: 0.92
  App::Git::Workflow::Command::Pom:
    file: lib/App/Git/Workflow/Command/Pom.pm
    version: 0.92
  App::Git::Workflow::Command::Recent:
    file: lib/App/Git/Workflow/Command/Recent.pm
    version: 0.92
  App::Git::Workflow::Command::TagGrep:
    file: lib/App/Git/Workflow/Command/TagGrep.pm
    version: 0.92
  App::Git::Workflow::Command::UpToDate:
    file: lib/App/Git/Workflow/Command/UpToDate.pm
    version: 0.92
  App::Git::Workflow::Command::Watch:
    file: lib/App/Git/Workflow/Command/Watch.pm
    version: 0.92
  App::Git::Workflow::Pom:
    file: lib/App/Git/Workflow/Pom.pm
    version: 0.92
  App::Git::Workflow::Repository:
    file: lib/App/Git/Workflow/Repository.pm
    version: 0.92
  Mock::App::Git::Workflow::Repository:
    file: lib/Mock/App/Git/Workflow/Repository.pm
    version: 0.92
  Test::Git::Workflow::Command:
    file: lib/Test/Git/Workflow/Command.pm
    version: 0.92
recommends:
  JIRA::REST: 0
  JSON: 2.0
requires:
  Error: 0
  Git: 0
  Path::Class: 0
  Time::Piece: 0
  XML::Tiny: 0
  autodie: 0
  perl: 5.008
resources:
  bugtracker: https://github.com/ivanwills/git-workflow-tools/issues
  license: http://dev.perl.org/licenses/
  repository: git://github.com/ivanwills/git-workflow-tools.git
version: 0.92
